### ISSUE TITLE
Release pytest-pyodide 0.21.0

### ISSUE THREAD

**Issue by ryanking13** [pyodide/pytest-pyodide#19]
I hope we can release a stable version of `pytest-pyodide` along with Pyodide 0.21.0 release.

**Comment by rth** [comment]
Yes, definitely. I mean we can already release it now I think, there are no remaining blockers as far as I know.

**Comment by ryanking13** [comment]
> Yes, definitely. I mean we can already release it now I think, there are no remaining blockers as far as I know.

Alright, I'll merge #20 and #18 then release 0.21.0.

**Comment by ryanking13** [comment]
Released 0.21.0

- https://github.com/pyodide/pytest-pyodide/tree/v0.21.0
- https://pypi.org/project/pytest-pyodide/
