### ISSUE TITLE
Catch request body

### ISSUE THREAD

**Issue by koenvo** [pyodide/pytest-pyodide#41]
Is there a way to capture the request body when using `spawn_web_server`?

For https://github.com/koenvo/pyodide-http/pull/16 I need to make sure the request body is a correctly formatted json body.

edit: let me create a PR for this

**Comment by ryanking13** [comment]
> edit: let me create a PR for this

Thanks a lot!

**Comment by ryanking13** [comment]
Closing as resolved via #47. Thanks!
