### ISSUE TITLE
Next release version

### ISSUE THREAD

**Issue by rth** [pyodide/pytest-pyodide#50]
There are a number of PRs that's going to be merged, so it would be good to tag soon.

The question is which version we should use. I don't think trying to keep with Pyodide versions would work, I would rather we followed semver and made this version evolve separately. Though we would still need to indicate the compatible Pyodide releases somehow.

WDYT?

**Comment by ryanking13** [comment]
Yes, we have already released `pytest-pyodide` independently several times, so I think it is okay to have a separate version.

> Though we would still need to indicate the compatible Pyodide releases somehow.

Maybe a short table that contains "this version of `pytest-pyodide` is tested with Pyodide v0.21.0, v0.20.0, ..." would work?

| pytest-pyodide | Tested Pyodide versions |
|----------------|-------------------------|
| 0.22.0         | 0.21.0, 0.20.0          |
| 0.23.0         | 0.22.0, 0.21.0, 0.20.0  |
| ...            | ...                     |

**Comment by rth** [comment]
+1 to add that table to the readme.
