### ISSUE TITLE
Support running non-pyodide tests in pyodide automatically?

### ISSUE THREAD

**Issue by joemarshall** [pyodide/pytest-pyodide#58]
Looking at porting libraries to work with webassembly, it would be nice to have a 'run the library tests in pyodide' option. 

e.g. an option to pytest which instead of running all tests in pytest_pyodide and requiring e.g. selenium objects etc. it would instead install the package and run all tests found on a pyodide instance.

Otherwise I'm implementing separate test fixtures for pyodide tests, which essentially copy everything across to pyodide, import the package, then run the tests.

**Comment by ryanking13** [comment]
I am not sure I understood your proposal correctly. If the package contains test files then if those can be run with pytest or unittest, you can run it with pytest and unittest APIs ([example](https://github.com/pyodide/pyodide/blob/c85e00806b38b23efc2b2c656457fcd8117cfee3/packages/scipy/test_scipy.py#L48-L65)). Is this what you are looking for?

**Comment by hoodmane** [comment]
This is related to my command line runner. The idea there is that you make a special virtual environment, install the dependencies, and then run `python -m pytest` and everything works as expected. See 
https://github.com/hoodmane/numpy/blob/emscripten-ci/.github/workflows/emscripten.yml#L56-L66
in https://github.com/numpy/numpy/pull/21895/.

**Comment by joemarshall** [comment]
Wow, I like that python runner. Any way to make it work as a browser test as well as node though? Or would it be easier to add code to pytest-pyodide to do the equivalent (

**Comment by rth** [comment]
PR for this issue in https://github.com/pyodide/pytest-pyodide/pull/62
