### ISSUE TITLE
Add joemarshall as a co-maintainer

### ISSUE THREAD

**Issue by rth** [pyodide/pytest-pyodide#72]
I would like to propose adding @joemarshall to the maintainers of [pytest-pyodide](https://github.com/pyodide/pytest-pyodide) who has been doing lots of work on this repo as well as Pyodide ecosystem in general. Thanks for your work!  BTW, sorry if we were slow to respond to some of your comments lately, me in particular.

For any significant changes, we still require one review from another maintainer before merging.

We don't really have a process to add maintainers to packages in pyodide org (aside from the main monorepo), but I would say just a discussion or vote on this issue should be enough.

WDYT @ryanking13 @hoodmane ?

**Comment by joemarshall** [comment]
Thanks for this, I'd be happy to be involved - and no worries about being slow to respond to things - I don't know about you guys but I'm paid one day a week to do pyodide based stuff right now, so I tend to do a flurry of work, then go off back to my permanent job which pays me 3 days/week, so I'm quick to respond some days and take a week or so at other times. I dunno how long this current contract will need me to be doing pyodide work, but I'm keen to keep doing stuff in this area as long as there are people around who want things to happen in pyodide (and right now, any pyodide work still tends to involve upstreaming things to some extent)

**Comment by rth** [comment]
Great news that you have some funding to work on Pyodide!
If there is anything we can do to make your work in this space easier let us know :)

**Comment by ryanking13** [comment]
I'm in favor of it. Thanks for the your work on Pyodide ecosystem Joe!

**Comment by rth** [comment]
Done. @joemarshall you should now have write permissions on this repo )
