### ISSUE TITLE
Re-evaluate public API

### ISSUE THREAD

**Issue by rth** [pyodide/pytest-pyodide#8]
Before making a public release of the package it might be good to re-evaluate what is exposed as the public API.

Looking at https://github.com/pyodide/pytest-pyodide/blob/main/pytest_pyodide/__init__.py generally, it looks OK, however,
 - I think we should probably not expose all the `*Wrapper` as the top-level import. Having them under `pytest_pyodide.browser` sounds more reasonable particularly given that users would use them via fixture and not directly
 - Actually maybe renaming them  to,
   ```
    # private
     "_BrowserBaseRunner",
    "_SeleniumBaseRunner",
    "_PlaywrightBaseRunner",
    # public
    "SeleniumFirefoxRunner",
    "SeleniumChromeRunner",
    "PlaywrightChromeRunner",
    "PlaywrightFirefoxRunner",
    `NodeRunner`
    ```
    might be better? Wrapper is an odd name that could be improved IMO in this context. And if we do this rename `browser.py` to `runner.py`
 - not sure why we `from fixtures import *` but I would be +1 to remove it, and let users `from pytest_pyodide.fixtues import ..` explicitly

cc @ryanking13

**Comment by ryanking13** [comment]
> * I think we should probably not expose all the `*Wrapper` as the top-level import. Having them under `pytest_pyodide.browser` sounds more reasonable particularly given that users would use them via fixture and not directly

Yes, that sounds reasonable to me.

> * Wrapper is an odd name that could be improved IMO in this context. And if we do this rename `browser.py` to `runner.py`

I'm +1 with it.

> * not sure why we `from fixtures import *` but I would be +1 to remove it,

I think we don't need that line anymore, that line was needed before we package `pytest-pyodide`, but now [pytest11 entrypoint](https://github.com/pyodide/pytest-pyodide/blob/0803301a6220ed5ae803634b061c488159b9311a/setup.cfg#L39-L42) will register those fixtures automatically.
